name: Create Infra
on:
  workflow_dispatch:

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  TF_VAR_branch_name: malti
  #AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  Create-Infrastructure:
    name: Create Infrastructure
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform
           
    steps:
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
            terraform_version: "1.5.0"
      - name: Step to Checkout the code 
        uses: actions/checkout@v4
      - name: Prepare HTML
        run: |
          sed -i "s/PLACEHOLDER_USER/${{ github.actor }}/g" ../project-code/*html
          sed -i "s/PLACEHOLDER_BRANCH/${{ github.ref_name }}/g" ../project-code/*html
      - name: Setup ssh
        run: echo "$SSH_KEY" > id_rsa
      - name: Setup ssh
        run: ls -lh id_rsa
        
  Terraform-Plan:
    name: Terraform Plan
    runs-on: ubuntu-latest
    needs: Create-Infrastructure
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Perform terraform Init 
        run: terraform init 
      - name: Perform terraform plan
        run: terraform plan -var "branch_name=${{ github.ref_name }}" 

  Terraform-Apply:
    name: Terraform Apply
    runs-on: ubuntu-latest
    needs: Terraform-Plan
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Perform terraform Init 
        run: terraform init 
      - name: Perform terraform apply
        run: terraform apply -var "branch_name=${{ github.ref_name }}" --auto-approve
