name: Delete-Infra
on:
  workflow_dispatch:

env: 
  AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
  AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
  SSH_KEY: ${{ secrets.SSH_KEY }}
  TF_VAR_branch_name: malti
  # AWS_REGION: ${{ secrets.AWS_REGION }}

jobs:
  terraform-init:
    name: Terraform Init
    runs-on: ubuntu-latest
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Setup SSH Key
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          ls -lh id_rsa

      - name: Terraform Init
        run: terraform init

  terraform-destroy:
    name: Terraform Destroy
    runs-on: ubuntu-latest
    needs: terraform-init
    if: github.ref_name == 'master'
    defaults:
      run:
        shell: bash
        working-directory: ./terraform

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"

      - name: Setup SSH Key
        run: |
          echo "$SSH_KEY" > id_rsa
          chmod 600 id_rsa
          ls -lh id_rsa

      - name: Terraform Init
        run: terraform init

      - name: Terraform Destroy
        run: terraform destroy -var "branch_name=${{ github.ref_name }}" --auto-approve
